### ISSUE TITLE
Maybe there is a bug in the programs

### ISSUE THREAD

**Issue by gwbearthqukae** [miili/pysurf96#2]
Thanks for your code. It's very helpful, but I found a bug recently. When I computed the phase velocity of rayleigh wave with these parameters 
```python
thickness=np.array([0.3,0]
vp=np.array([2.6, 5.29])
vs=np.array([1.12, 3.14])
rho=np.array([2.12,2.58])
periods=1/np.arange(6,1,-1)
```
surf96 threw an error. But If I make the `thickness=np.array([0.301,0])`, or even `[0.3001, 0]`, it runs sucessfully! Why? This problem confused me . Could you help me find the answer?

**Comment by miili** [comment]
Hi, I cannot reproduce the error. Can you please paste the output?

**Comment by gwbearthqukae** [comment]
I'm doing the Monte Carlo inversion, and try to calculate thousands of models. I found that the thickness=[0.25,0] also produced the error, "surf96 threw an error! This may be due to low velocity zone causing reverse phase velocity dispersion and mode jumping. Due to looking for Love waves in a halfspace which is OK if there are Rayleigh data" . But  thickness=[0.251,0] is OK.

I run the programms on a laptop  with ubuntu system, and python3.7, gfortran.

I have put the error information in the attachment.

________________________________
发件人: Mi! <notifications@github.com>
发送时间: 2020年1月20日 20:44
收件人: miili/pysurf96 <pysurf96@noreply.github.com>
抄送: gwbearthqukae <gwb4133@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [miili/pysurf96] Maybe there is a bug in the programs (#2)


Hi, I cannot reproduce the error. Can you please paste the output?

―

**Comment by miili** [comment]
This is due to wrong input data.
