### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Karim-19** [miili/pysurf96#3]
Hi, thanks for your great work. 
I'm planning to use the code, but couldn't install it. tried using:
pip install git+https://github.com/miili/pysurf96
but keep receiving this error:
 flang.exe: error: unsupported fixed-format line length in argument '-ffixed-line-length-none'

Hope you could help me to fix it!

**Comment by miili** [comment]
Dear Karim-19,

try another Fortran compiler. I have no experience with Windows and have no deeds in changing this.
Did you get it to work in the meantime?

Best, Marius
