### ISSUE TITLE
Compiler problem

### ISSUE THREAD

**Issue by Ric89-crypto** [miili/pysurf96#5]
Hi and thank you for this package!
I'm approaching python and coding in general, so sorry if my issue is trivial.

I'm trying to install pysurf96 using anaconda prompt shell and command prompt (on windows) and terminal (on mac). For both machines I get the same error (attached are the output of the terminal). I've installed obspy, numpy and a gfortran compiler (conda install -c conda-forge gcc). Could you help me? 
All the best
Riccardo
[Logout2.txt](https://github.com/miili/pysurf96/files/9744543/Logout2.txt)
[Logout1.txt](https://github.com/miili/pysurf96/files/9744544/Logout1.txt)

**Comment by davince123** [comment]
hi, Do you resolve this problem ?

**Comment by miili** [comment]
Fixed in #10
