### ISSUE TITLE
About "iflsph"

### ISSUE THREAD

**Issue by ttcat98** [miili/pysurf96#7]
In the Fortran77 subroutine file, "iflsph = 0" actually indicates the flat earth model, which is the same in the CPS. So I think  `iflsph = 1 if flat_earth else 0` is mistyped, am I wrong?

`c    is the model flat (nsph = 0) or sphere (nsph = 1)`	 
`       nsph = iflsph`

**Comment by miili** [comment]
Good catch! Fixed in #10
